### ISSUE TITLE
(thinking of removing this request...)

### ISSUE THREAD

**Issue by SabirMayoTheTester** [geofs-plugins/aircraft-warehouse#10]
_**There have been a few changes to this comment, but still, read on...**_

**The model I want**: Airbus A320 SL

**The livery I want**: Eurowings Airlines (Lufthansa subsidiary that is low-cost for those who don't know.)

**Special reason for desiring this aircraft**:
 The Airbus A320 is one of the most advanced short-haul aircraft used by airlines, and it is innovative, super and iconic. It has damn awesome engines and is a joy to fly with many, many, MANY in use.. Flying it in GeoFS would be a great idea, since it would be awesome. 👍 :)

**Enter some pictures of a real-life aircraft here**:
![image](https://user-images.githubusercontent.com/26579029/27768578-d66c378e-5f0e-11e7-8972-115d9d62fb69.png)
![image](https://user-images.githubusercontent.com/26579029/27768580-e22a0664-5f0e-11e7-9fd0-b316a20977b9.png)
![image](https://user-images.githubusercontent.com/26579029/27768584-fc76aef0-5f0e-11e7-854a-88c909786837.png)

**Comment by DAL1060** [comment]
Or Delta Airlines livery

**Comment by SabirMayoTheTester** [comment]
we could... if i could do another plane request..

(ps. sorry that i replied in 2018....)

**Comment by SabirMayoTheTester** [comment]
@DAL1060 **We could, but I chose the Eurowings livery, as you can see in the request..**

**Comment by SabirMayoTheTester** [comment]
how do i delete issues?

**Comment by yotam180** [comment]
You close them, like that 👇
