### ISSUE TITLE
It generally is polite to ask first

### ISSUE THREAD

**Issue by legoboyvdlp** [geofs-plugins/aircraft-warehouse#15]
Hi there,
I noticed you seem to have taken the textures from our 737-800 (737-800YV).
It generally is polite to ask first, but since it is indeed legal for you to do so, you can use them.
Jonathan

**Comment by ryanturner328** [comment]
Who @legoboyvdlp

**Comment by legoboyvdlp** [comment]
Those textures for the 737-800 seem to match our textures: https://github.com/YV3399/737-800YV/tree/master/Models/Liveries-800

But anyway, you can use them if you want as far as I'm concerned.

**Comment by yotam180** [comment]
That's right.
It never occurred to me that using those textures would cause a problem, because, as stated by you, the license approved using them.

If you wish me to any credit or something in the repo or plane files, just tell me, I'd love to honor your work.

Sorry for the inconvenience,
Yotam.

**Comment by legoboyvdlp** [comment]
Not a problem at all :)
No, that's fine -- feel free to use them.
