### ISSUE TITLE
Boeing 737-MAX-8

### ISSUE THREAD

**Issue by chooeybooey** [geofs-plugins/aircraft-warehouse#30]
**The model I want**: Boeing 737 MAX 8
**The livery I want**: Southwest
**Special reason for desiring this aircraft**: A modern jet with AMAZING winglets! (also since you already did the 737-800 you have sketchup models ;))

**Enter some pictures of a real-life aircraft here**:
![image](https://user-images.githubusercontent.com/31420396/31295574-a6c255c2-aaa4-11e7-94c9-47db0d11a61e.png)

**Comment by yotam180** [comment]
There's already a very **very** close family member (i.e. Boeing 737-700) of the same livery.
I don't see how this is worth the time of working in relation to the small diversity it would add to the game.

Sorry. 😞

**Comment by chooeybooey** [comment]
Okay, I see your point. Thanks!
