### ISSUE TITLE
Aircraft im working on

### ISSUE THREAD

**Issue by Featherway** [geofs-plugins/aircraft-warehouse#33]
**The model I want**: 737 max 8_________

**The livery I want**: _______southwest_____

**Special reason for desiring this aircraft**:<br/>
*Enter here* This is my favorite plane ever! And im developing it

**Enter some pictures of a real-life aircraft here**:
![image](https://user-images.githubusercontent.com/31420965/32303421-e66bc308-bf3e-11e7-9f1e-d58aff90cdb1.png)

**Comment by ron-popov** [comment]
If you are working on it, then you don't need to open an issue. When you are done please email @yotam180 for more information on how to add this plane to the game.

**Comment by OneHotChick** [comment]
Is that sketchup you're using?
