### ISSUE TITLE
Nice planes liveries (Especialy removed)

### ISSUE THREAD

**Issue by 77TG** [geofs-plugins/aircraft-warehouse#35]
**The model I want**:Boeing 737 MAX 8, A320 neo, Boeing 777

**The livery I want**: Southwest and LOT (For 737 MAX), Easyjet (For A320 neo), Lufthansa (For A320 neo), Emirates and Air Canada (For Boeing 777), Fix Boeing 737 Ryanair

**Special reason for desiring this aircraft**:<br/>
Southwest - There was Boeing 737-800 Southwest livery, but they removed it.
so you can readd it but for Boeing 737 MAX 8
LOT - I want it beacuse it will be first aircraft in GeoFS from LOT and Its airline from my country
Easyjet - Im often flying around Europe so I want really two biggest low cost airlines in Europe in SkyX. It will be nice
Lufthansa - Simple I love Lufthansa livery
Emirates - There are much 777 in Emirates fleet. Boeing 777 Emirates also was in GeoFS, but they removed it, you could also add that livery back
Air Canada - That will be first Air Canada plane in game, 777 Air Canada also was in GeoFS
Fix Ryanair - The tail logo is not where should be (See in real life pictures)
**Enter some pictures of a real-life aircraft here**:
![4261559](https://user-images.githubusercontent.com/37912551/38108789-3870135e-3396-11e8-8be2-6ba3e451f9f0.jpg)
![maxresdefault](https://user-images.githubusercontent.com/37912551/38108985-deaf368c-3396-11e8-865e-3627432e9955.jpg)
![f979d94975870ec3b78df3d04fc5fad9](https://user-images.githubusercontent.com/37912551/38108856-680fe508-3396-11e8-87a0-67a8237d135c.jpg)
![lufthansa_a320_d-aina_muc_2016-01-26_01cr](https://user-images.githubusercontent.com/37912551/38108886-87a1e9e8-3396-11e8-9b67-39140a352666.jpg)
![301716](https://user-images.githubusercontent.com/37912551/38109036-05331256-3397-11e8-8dfe-275f8ecbc06a.jpg)
![maxresdefault 1](https://user-images.githubusercontent.com/37912551/38109084-46464f56-3397-11e8-898f-5733f1c47345.jpg)
![738ryanair-1](https://user-images.githubusercontent.com/37912551/38109155-84593eca-3397-11e8-966c-fe77371a2d86.jpg)

**Comment by RNA-Fighter-46** [comment]
I think that the tail part was Upside down and the winglet stretched.

**Comment by yotam180** [comment]
Can you separate each aircraft/livery request to issues? Only one request per issue so we can track them better. Thanks :slightly_smiling_face:

**Comment by RNA-Fighter-46** [comment]
ok

**Comment by 77TG** [comment]
RNA-Fighter-46 Yeah, look at Ryanair livery pic here and at geofs Ryanair :)
