### ISSUE TITLE
md-80

### ISSUE THREAD

**Issue by CodyJMoore** [geofs-plugins/aircraft-warehouse#42]
**The model I want**: _MD-80_

**The livery I want**: ______aLLEGAINT______

**Special reason for desiring this aircraft**:<br/>
It is the first aircraft i flyed in

![download 1](https://user-images.githubusercontent.com/39317446/40086050-958a0592-5851-11e8-83da-ffba7b4cf377.jpg)
![images](https://user-images.githubusercontent.com/39317446/40086061-a44bb616-5851-11e8-9fb0-19caaf276d36.jpg)

**Comment by 77TG** [comment]
There was allegiant MD-80 request

**Comment by yotam180** [comment]
@77TG is right.

**Comment by CodyJMoore** [comment]
Hey can you help me make it it is my birthday the 19 of may nad i was wondering if you can make it for me and it would be a birthday gift!!
 If you would thank you!
