### ISSUE TITLE
TTCM: Livery Request: Qatar Airlines World Cup 2022

### ISSUE THREAD

**Issue by TheTrainCrazyMan** [geofs-plugins/aircraft-warehouse#44]
**The model I want**: Boeing 777

**The livery I want**: Qatar Airlines World Cup 2022

**Special reason for desiring this aircraft**:<br/>
I really like the flow of colors that accentuates the logo on the tail. This livery is colorful and would be a good fit for GeoFS.

**Enter some pictures of a real-life aircraft here**:
![qatar777cup2022](https://user-images.githubusercontent.com/25624120/45929462-2c6d0100-bf20-11e8-9d72-ef542ca71d17.jpg)
![qatarcup2022](https://user-images.githubusercontent.com/25624120/45929464-2ecf5b00-bf20-11e8-9d07-9de180af4607.jpg)

**Comment by yotam180** [comment]
As Qatar does not deserve the right to host the World Cup 2022 in the developers' opinions, we will refrain from making a Qatar Airways livery carrying the world cup special outfit.

Sorry.
