### ISSUE TITLE
Livery

### ISSUE THREAD

**Issue by xxDOMINATORxxe** [geofs-plugins/aircraft-warehouse#47]
**The model I want**: ______737-700_____

**The livery I want**: ____Southwest________

**Special reason for desiring this aircraft**:<br/>
*Enter here*I with they had the livery

**Enter some pictures of a real-life aircraft here**:
![screenshot 2018-12-02 at 11 29 47 am](https://user-images.githubusercontent.com/45407314/49342173-a529c100-f625-11e8-9bbc-62c89dfeb0d2.png)

**Comment by yotam180** [comment]
Work in progress

**Comment by yotam180** [comment]
Done. will be up on GeoFS in the next couple of days.

**Comment by Larryismyfriend1209** [comment]
Closed #47

**Comment by Larryismyfriend1209** [comment]
When is it going to be posted on geo-fs? Is it going to be community
contributed or sky-x? Please let me know by today please. I would like to
know. 😎

**Comment by yotam180** [comment]
Will be officially available through SkyX 2.0 (thanks to our contributor Air-Geo Fs).

You can update to SkyX 2.0 from the Chrome Store.

**Comment by Larryismyfriend1209** [comment]
Yotam salmon if you can change the livery's on the aircraft in geo-fs.com
with the community contributed here are some aircraft livery's I want
changed.
Boeing 787-8 - American Airlines

**Comment by yotam180** [comment]
Can't do that. I am not a community contributor.

**Comment by Larryismyfriend1209** [comment]
Oh how do I become a community contributor? Cause I want to make planes.

**Comment by Larryismyfriend1209** [comment]
Also how do i contact them?

**Comment by yotam180** [comment]
You need some knowledge in Javascript, modeling and texturing in order to make planes. You can contact Harry Xue, but he is not likely to respond. It's hard to get to the Community Contributors these days.

**Comment by Larryismyfriend1209** [comment]
Oh

**Comment by Larryismyfriend1209** [comment]
Hey can you put the southwest 737-700 on geo-fs community contribute.
Please so i can fly it too.

**Comment by Larryismyfriend1209** [comment]
Also can you make me a plane?

**Comment by Larryismyfriend1209** [comment]
I wan the md-80 of allegiant airline?

**Comment by Larryismyfriend1209** [comment]
Here are some pictures of the real aircraft
