### ISSUE TITLE
New Boeing 747-400 DAL

### ISSUE THREAD

**Issue by DAL1060** [geofs-plugins/aircraft-warehouse#5]
**The model I want**: __Boeing 747-400_________

**The livery I want**: __Delta Airlines__________

**Special reason for desiring this aircraft**:<br/>
*Enter here* I have always loved the 747-400 and always wanted to fly it.

**Enter some pictures of a real-life aircraft here**: 
![744](https://user-images.githubusercontent.com/29676269/27509110-74d2ea00-58c3-11e7-8cfb-9c9cff28a78c.gif)
![boeing_747-400_delta_air_lines_x](https://user-images.githubusercontent.com/29676269/27509114-8a33d7a6-58c3-11e7-96e5-077e34d3bf26.jpg)

**Comment by yotam180** [comment]
This proposal has been considered and rejected for now.

Sorry for the disappointment, but we may look at it in the future.
Yotam.
