### ISSUE TITLE
717 Removed from skyx ?

### ISSUE THREAD

**Issue by mm-git01** [geofs-plugins/aircraft-warehouse#50]
In the latest 2.0 version the 717 and 787 aircraft seems to be missing

**Comment by mm-git01** [comment]
the 717 has been mislabeled an put under the crj-200 section. The hawaiin airlines crj-200 is the 717

**Comment by yotam180** [comment]
Really? Oops.. I will fix it soon. I'm, reopening the issue since it's not yet resolved

**Comment by yotam180** [comment]
It's ok now
