### ISSUE TITLE
Aircraft Warehouse will not load!

### ISSUE THREAD

**Issue by DAL1060** [geofs-plugins/aircraft-warehouse#9]
When I try to go to Aircraft Warehouse on Aircraft ( in the game ) It is never there! Plz, help!
![screen shot 2017-06-25 at 3 03 39 pm](https://user-images.githubusercontent.com/29676269/27518878-80e8c4d2-59b7-11e7-9b01-dde95f6d8312.png)
![screen shot 2017-06-25 at 3 04 22 pm](https://user-images.githubusercontent.com/29676269/27518882-99b35bda-59b7-11e7-8acb-948ad0f06b0f.png)

**Comment by yotam180** [comment]
Fixed.
